---
- name: Tear down local Kubernetes cluster
  hosts: kubernetes
  become: yes
  tasks:
    - name: Reset the Kubernetes cluster state
      ansible.builtin.command: kubeadm reset -f
      register: kubeadm_reset_result
      failed_when: kubeadm_reset_result.rc != 0 and "could not find a Kubernetes cluster" not in kubeadm_reset_result.stderr
      changed_when: kubeadm_reset_result.rc == 0

    - name: Remove CNI networking configuration
      ansible.builtin.file:
        path: /etc/cni/net.d
        state: absent

    - name: Remove user's .kube configuration directory
      become: false
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube"
        state: absent

    - name: Find orphaned Calico network interfaces
      ansible.builtin.shell: "ip -br a | grep '^cali' | awk '{print $1}' | cut -d'@' -f1"
      register: calico_interfaces
      changed_when: false
      ignore_errors: true

    - name: Delete orphaned Calico network interfaces
      ansible.builtin.command: "ip link delete {{ item }}"
      loop: "{{ calico_interfaces.stdout_lines }}"
      when: calico_interfaces.stdout != ""
      ignore_errors: true

    # NOTE: The tunl0 interface is managed by the ipip kernel module and can
    # sometimes persist after teardown. It is harmless and can be ignored.
    # A full reboot will always clean it up.
