---
- name: Install kubeadm, kubelet, kubectl
  ansible.builtin.pacman:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present

- name: Enable kubelet service
  ansible.builtin.systemd:
    name: kubelet
    enabled: true

- name: Initialize Kubernetes cluster
  ansible.builtin.command:
    cmd: "kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ ansible_default_ipv4.address }}"
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init_output

- name: Fetch admin.conf from master node
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: "/tmp/kube-admin.conf"
    flat: yes
  become: true

- name: Copy admin.conf to user's .kube directory
  ansible.builtin.copy:
    src: /tmp/kube-admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: false

- name: Install Calico Pod Network Addon
  ansible.builtin.command: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://docs.projectcalico.org/manifests/calico.yaml"
  changed_when: true
  when: kubeadm_init_output.changed

- name: Wait for the master node to be Ready
  ansible.builtin.shell: "kubectl --kubeconfig=/etc/kubernetes/admin.conf get node {{ ansible_hostname }} -o jsonpath='{.status.conditions[?(@.type==\"Ready\")].status}'"
  register: node_status
  until: node_status.stdout == "True"
  retries: 60
  delay: 5
  when: kubeadm_init_output.changed

- name: Get kubeadm join command for workers
  ansible.builtin.command: kubeadm token create --print-join-command
  register: kubeadm_join_command
  changed_when: true

- name: Save join command for later use
  ansible.builtin.set_fact:
    join_command: "{{ kubeadm_join_command.stdout }}"
