---
common_packages:
  - curl
  - wget
  - gnupg
  - ca-certificates

swap_systemd_service: ""

virtualization_host_packages:
  - qemu-kvm
  - libvirt-daemon-system
  - libvirt-clients
  - python3-libvirt
  - python3-lxml
  - genisoimage
