---
- name: Install containerd
  ansible.builtin.apt:
    name: containerd
    state: present
    update_cache: yes

- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory

- name: Ensure containerd config file is present with default values
  ansible.builtin.shell:
    cmd: "containerd config default > /etc/containerd/config.toml"
    creates: /etc/containerd/config.toml
  changed_when: true

- name: Ensure SystemdCgroup is set to true
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '(\s*SystemdCgroup\s*=\s*)false'
    replace: '\1true'
  notify: Restart containerd

- name: Ensure containerd service is active and enabled
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true
